import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { fromJSON } from "postcss";

/* 设置字体为 Noto Sans SC */
const notoSansSC = localFont({
  src: [
    {
      path: "./fonts/NotoSansSC-Light.otf",
      weight: "300",
    },
    {
      path: "./fonts/NotoSansSC-Regular.otf",
      weight: "400",
    },
    {
      path: "./fonts/NotoSansSC-Medium.otf",
      weight: "500",
    },
    {
      path: "./fonts/NotoSansSC-Bold.otf",
      weight: "700",
    },
  ],
  variable: "--font-noto-sans-sc",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${notoSansSC.variable} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
